sudo: false
dist: trusty

language: julia

addons:
  apt:
    packages:
      llvm-3.9
      llvm-3.9-tools
      libclang-3.9-dev


julia:
  - 0.5
    #  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("Clang")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';

script:
    - julia --compilecache=no -e 'Pkg.clone(pwd()); Pkg.build("Clang"); Pkg.test("Clang"; coverage=true)';
