name = "Clang"
uuid = "40e3b903-d033-50b4-a0cc-940c62c95e31"
authors = ["Isaiah Norton"]
version = "0.10.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LLVM_jll = "86de99a1-58d6-5da7-8064-bd56ce2e322c"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CEnum = "0.2"
DataStructures = "0.17"
LLVM_jll = "6.0.1"
julia = "~1.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
