name = "Clang"
uuid = "40e3b903-d033-50b4-a0cc-940c62c95e31"
authors = ["Isaiah Norton"]
version = "0.9.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CEnum = ">= 0.2.0"
BinaryProvider = ">= 0.3.0"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
