name = "Clang"
uuid = "40e3b903-d033-50b4-a0cc-940c62c95e31"
authors = ["Isaiah Norton"]
version = "0.12.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CEnum = "0.4"
DataStructures = "0.17, 0.18"
julia = "~1.5.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
