name = "Clang"
uuid = "40e3b903-d033-50b4-a0cc-940c62c95e31"
version = "0.16.5"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CEnum = "0.4"
Clang_jll = "12,13,14"
Downloads = "1.4"
TOML = "1.0"
julia = "1.7.0"

[extras]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
CMake = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

[targets]
test = ["Test"]
